version: '2.1'
services:
  nprs:
    env_file:
      - ./env/common.env
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - chrome
    links:
      - redis
      - chrome
    environment:
      HOST: "m.bilibili.com"
      PORT: 443
      PROTOCOL: "https"
      REDIS_URL: "redis://redis:6379/0"
      CHROME_URL: "http://chrome:9222"
    command: ["yarn", "run", "start"]
  redis:
    image: redis:3.2-alpine
    expose:
      - "6379"
  chrome:
    build:
      context: ./chrome
    expose:
      - "9222"