version: '2.1'
services:
  nprs:
    env_file:
      - ./env/common.env
    build:
      context: .
      args:
        NPM_REGISTRY: "https://registry.npm.taobao.org"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    links:
      - redis
    environment:
      HOST: "m.bilibili.com"
      PORT: 443
      PROTOCOL: "https"
      REDIS_URL: "redis://redis:6379/0"
    command: ["yarn", "run", "start"]
  redis:
    image: redis:3.2-alpine
    expose:
      - "6379"